name: ZYZ_CSharp_Extension

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  build_and_pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ${{ github.workspace }}/build
      # ^^^^^ 更改: 明确指定了输出目录为 GitHub Actions 工作区的 `build` 文件夹

    - name: Pack
      run: dotnet pack --no-build --configuration Release --output ${{ github.workspace }}/nupkgs
      # ^^^^^ 更改: 确保 dotnet pack 使用和 dotnet build 相同的输出目录，这里不再需要单独设置 PackageOutputPath

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (NuGet Package)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/nupkgs/*.nupkg
        asset_name: ZYZ_CSharp_Extension.nupkg
        asset_content_type: application/zip
