name: ZYZ_CSharp_Extension

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Extract version from .csproj
      id: version
      run: |
        $version = [xml](Get-Content ./ZYZ-CSharp-Extension.csproj)
        $projectVersion = $version.Project.PropertyGroup.Version
        echo "PROJECT_VERSION=$projectVersion" >> $GITHUB_ENV
        echo "::set-output name=project_version::$projectVersion"
      shell: pwsh

    - name: Build and generate NuGet package
      run: dotnet build --configuration Release --output ${{ github.workspace }}/build
      # 构建的同时生成 NuGet 包，因为 GeneratePackageOnBuild 设置为 True

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.project_version }}
        release_name: Release v${{ steps.version.outputs.project_version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (NuGet Package)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/build/ZYZ_CSharp_Extension.${{ steps.version.outputs.project_version }}.nupkg
        asset_name: ZYZ_CSharp_Extension-${{ steps.version.outputs.project_version }}.nupkg
        asset_content_type: application/zip

    - name: Upload Release Asset (DLL files)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/build/ZYZ_CSharp_Extension.dll
        asset_name: ZYZ_CSharp_Extension-${{ steps.version.outputs.project_version }}.dll
        asset_content_type: application/octet-stream
